# -- Site Configuration --
theme = "congo"
baseURL = "https://gabiapps.com/"
defaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "Gabi Apps"
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    [[languages.en.menu.main]]
      name = "About"
      pageRef = "about"
      weight = 10
    [[languages.en.menu.main]]
      name = "Apps"
      pageRef = "apps"
      weight = 20
    [[languages.en.menu.main]]
      name = "Blog"
      pageRef = "blog"
      weight = 30
    [[languages.en.menu.main]]
      name = "Support"
      pageRef = "support"
      weight = 40
    [[languages.en.menu.main]]
      name = "GitHub"
      url = "https://github.com/hercoolvery"
      weight = 50
      [languages.en.menu.main.params]
        icon = "github"
        showName = false
        target = "_blank"
    [[languages.en.menu.main]]
      identifier = "search"
      weight = 99
      [languages.en.menu.main.params]
        action = "search"
    [[languages.en.menu.main]]
      identifier = "locale"
      weight = 100
      [languages.en.menu.main.params]
        action = "locale"
  [languages.ko]
    title = "가비앱스"
    languageName = "한국어"
    languageCode = "ko-kr"
    weight = 2
    [[languages.ko.menu.main]]
      name = "소개"
      pageRef = "about"
      weight = 10
    [[languages.ko.menu.main]]
      name = "앱"
      pageRef = "apps"
      weight = 20
    [[languages.ko.menu.main]]
      name = "블로그"
      pageRef = "blog"
      weight = 30
    [[languages.ko.menu.main]]
      name = "지원"
      pageRef = "support"
      weight = 40
    [[languages.ko.menu.main]]
      name = "GitHub"
      url = "https://github.com/hercoolvery"
      weight = 50
      [languages.ko.menu.main.params]
        icon = "github"
        showName = false
        target = "_blank"
    [[languages.ko.menu.main]]
      identifier = "search"
      weight = 99
      [languages.ko.menu.main.params]
        action = "search"
    [[languages.ko.menu.main]]
      identifier = "locale"
      weight = 100
      [languages.ko.menu.main.params]
        action = "locale"

enableRobotsTXT = true
summaryLength = 0
Copyright = "Copyright © 2025 - Gabi Apps All Rights Reserved."

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  fingerprintAlgorithm = "sha256"
  colorScheme = "congo"
  defaultAppearance = "light"
  autoSwitchAppearance = true

  enableSearch = true
  enableCodeCopy = true
  enableImageLazyLoading = true
  enableImageWebp = true
  enableQuicklink = true
  [params.author]
    name = "Cho Sungryong"
    headline = "System S/W Engineer & Chief Creator of Gabi Apps"
    image = "images/gabiapps_about_my_img.png"
  [params.header]
    layout = "basic"
    showTitle = true
  [params.footer]
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true
  [params.homepage]
    layout = "custom" # Changed from custom to profile for a clean start
    showRecent = true
    recentLimit = 5
  [params.article]
    showDate = true
    showDateUpdated = false
    showAuthor = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = false # Disabled edit link
    showHeadingAnchors = true
    showPagination = true
    invertPagination = false
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = false
    showWordCount = false
    showComments = false
  [params.list]
    showBreadcrumbs = true
    showSummary = false
    showTableOfContents = true
    showTaxonomies = false
    groupByYear = false
    paginationWidth = 1
  [params.sitemap]
    excludedKinds = ["taxonomy", "term"]
  [params.taxonomy]
    showTermCount = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
